# Generated by Django 2.0.1 on 2022-09-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='author_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
