# Generated by Django 2.0.1 on 2022-09-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_framework_author_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='br2_field',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
