# Generated by Django 2.0.1 on 2022-09-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_framework_br1_field'),
        ('task', '0003_framework_br2_field'),
    ]

    operations = [
    ]
