# Generated by Django 2.0.1 on 2022-12-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_framework_field1'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='field2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
